routes/web.php
<?php

use App\Http\Controllers\Dashboard\PostController;
use App\Http\Controllers\Dashboard\TestController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


//ruta de tipo Recurso
Route::resource('post', PostController::class);

//nos ahorramos estos
/*
Route::get('post', PostController::class, 'index');
Route::get('post/{post}', PostController::class, 'show');
Route::get('post/create', PostController::class, 'create');
Route::get('post/post/edit', PostController::class, 'edit');


Route::post('post', [PostController::class, 'store']);
Route::put('post/{post}', [PostController::class, 'update']);
Route::delete('post/{post}', [PostController::class, 'delete']);
*/
/* Practicando
Route::get('/',[TestController::class, 'index']);

//Route::get('/test', [TestController::class, 'test']);

Route::get('/contacto', function() {
  return view('contacto');
})->name('contacto');


//como enviar parametrod
Route::get('/custom', function() {
  $mensaje = "Mensaje del servidor :)";
  $data = ['msj' => $mensaje, 'edad' => 15];
  //indicar la clave valor
  return view('custom', $data);
});
*/

app/Models/Categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    //use HasFactory;
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    //definiendo la propiedad fillable, para evitar la inyeccion de
    //atributos no deseados, limpieza de los campos
    protected $fillable = ['title', 'slug','content', 'categoria_id', 'description', 'posted', 'image'];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Dashboard/PostController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\Post\StorePostRequest;
use App\Http\Requests\Post\UpdatePutRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

use App\Models\Post;
use App\Models\Categoria;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //echo "hola index - post";
        $posts = Post::paginate(2);
        //echo view('dashboard/post.index', ["posts" => $posts]);
        return view('dashboard/post.index', ["posts" => $posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = Categoria::pluck('id', 'titulo');
        //dd($categorias);
        echo view('dashboard/post.create', compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        //
        //visualizar datos de forma amigable
        //dd($request);
        //dd(request("title"));
        //echo request('title');
        //echo $request->input('slug');
        //mostrar todos los datos del form
        //dd($request->all());
        //insertar datos Post::created($request->all());
        //insertar datos faltando un campo
        /*
        $data = array_merge($request->all(), ['image' => '']);
        dd($data);
        Post::created($data);*/
        //Validar la data, mediante el request de StorePostRequest
        //donde se difinen las reglas
        //otra forma
        //$request->validate(StorePostRequest::rules())
      //  Post::created($request->all());


        Post::create($request->validated());


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
        echo "show";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categorias = Categoria::pluck('id', 'titulo');
        echo view('dashboard/post.edit', compact('categorias', 'post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePutRequest $request, Post $post)
    {
        //dd($request->validated());
        //instancia de clase
        $post->update($request->validated());

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        echo "destroy";
    }
}

app/Http/Controllers/Dashboard/TestController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class TestController extends Controller
{
    /*
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //echo "Hola mundo";
        //return view('dashboard.test.index', ['name' => "Jhonathan", 'age' => 28 ,'html' => '<h1>Titulo</h1>', 'array' => [1,2,3,4,5,'arreglo-foreach'], 'users' => [10,11,12,13,14,15,'arreglo-forelse']]);
        $posts = [1,2,3,4,'jhonathan'];
        $users = [10,11,12,13,14,15,'arreglo-forelse'];
        //return view('dashboard.test.index', ['posts' => $posts, 'users' => [10,11,12,13,14,15,'arreglo-forelse']]);
        //organizar de una mejor manera
        //return view('dashboard.test.index', ['posts' => $posts, 'users' => $users]);
        //con la funcion compact
        return view('dashboard.test.index', compact('posts','users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/contacto.blade.php
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Contacto</h1>
  </body>
</html>

resources/views/custom.blade.php
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
  </head>
  <body>
    <h1>Pagina custom</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Mensaje </p>
    <h1><?php echo $msj ?> </h1>
    <h1><?= $msj ?></h1>
    <h1>{{ $msj }} {{ $edad }}</h1>
  </body>
</html>

resources/views/dashboard/fragment/errors-form.blade.php
<!--Funcionalidad de laravel para mostrar errores -->
@if ($errors->any())
  @foreach ($errors->all() as $error)
    <div class="error">
        {{ $error }}
    </div>
  @endforeach
@endif

resources/views/dashboard/layout.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Dashboard</title>
  </head>
  <body>
    <h1>Dasboard - Modulo Administrativo</h1>
    <!--Para colocar el contenido-->
    @yield('content')

  </body>
</html>

resources/views/dashboard/post/create.blade.php
<!--llamar al formato madre -->

@extends('dashboard/layout')

<!--colocar las seccion-->
@section('content')

  <div class="container">
      <h1>Crear Post</h1>

    @include('dashboard/fragment.errors-form')

    <form class="" action="{{ route('post.store') }}" method="post">
      <!--proteccion csrh-->
      @csrf
      <div class="">
        <label for="">Titulo</label>
        <input type="text" name="title" value="{{ old("title","") }}">
      </div>
      <div class="">
        <label for="">Slug</label>
        <input type="text" name="slug" value=" {{old("slug","")}} ">
      </div>
      <div class="">
        <label for="">Seleccione Categoria: </label>
        <select class="" name="categoria_id">
            <option value="">Seleccione:</option>

           @foreach ($categorias as $titulo => $id)
           <option {{ old("categoria_id","") == $id ? 'selected' : '' }} value="{{ $id }}">{{ $titulo }}</option>

            @endforeach
        </select>
      </div>
      <div class="">
        <label for="">Va a publicarlo: ?</label>
        <select class="" name="posted">
          <option {{ old("posted","") == "not" ? "selected" : ""}} value="not">No</option>
          <option {{ old("posted","") == "yes" ? "selected" : ""}} value="yes">Si</option>
        </select>

      </div>
      <div class="">
        <label for="">Contenido</label>
        <textarea name="content" rows="8"> {{ old("content","") }} </textarea>
      </div>
      <div class="">
        <label for="">Descripcion</label>
        <textarea name="description" rows="8">{{ old("description","") }}</textarea>
      </div>

      <button type="submit" name="button" class="button">Enviar</button>
    </form>
  </div>

@endsection

resources/views/dashboard/post/edit.blade.php
<!--llamar al formato madre -->

@extends('dashboard/layout')

<!--colocar las seccion-->
@section('content')

  <div class="container">
      <h1>Actualizar Post: {{ $post->title }}</h1>

    @include('dashboard/fragment.errors-form')

    <form class="" action="{{ route('post.update', $post->id) }}" method="post">
      <!--proteccion csrh-->
      @csrf
      <!--Agregando el metodo para una correcta interpretacion de laravel-->
      @method("PUT")
      <div class="">
        <label for="">Titulo</label>
        <input type="text" name="title" value="{{ $post->title }}">
      </div>
      <div class="">
        <label for="">Slug</label>
        <input readonly type="text" name="slug" value="{{ $post->slug }}">
      </div>
      <div class="">
        <label for="">Seleccione Categoria: </label>
        <select class="" name="categoria_id">
            <option value="">Seleccione:</option>

           @foreach ($categorias as $titulo => $id)
           <option {{ $post->categoria_id == $id ? 'selected' : '' }} value="{{ $id }}">{{ $titulo }}</option>

            @endforeach
        </select>
      </div>
      <div class="">
        <label for="">Va a publicarlo: ?</label>
        <select class="" name="posted">
          <option {{ $post->posted == 'not' ? 'selected' : '' }} value="not">No</option>
          <option {{ $post->posted == 'yes' ? 'selected' : '' }} value="yes">Si</option>
        </select>

      </div>
      <div class="">
        <label for="">Contenido</label>
        <textarea name="content" rows="8">{{ $post->content }}</textarea>
      </div>
      <div class="">
        <label for="">Descripcion</label>
        <textarea name="description" rows="8">{{ $post->description }}</textarea>
      </div>

      <button type="submit" name="button" class="button">Enviar</button>
    </form>
  </div>

@endsection

resources/views/dashboard/post/index.blade.php
@extends('dashboard/layout')

@section('content')

  <h1>Hola mundo index - Post</h1>
    <div class="">
        <div class="">
            <div class="">
              <a href="{{route("post.create")}}">Crear</a>
                <table>
                  <thead>
                    <tr>
                      <th>Titulo</th>
                      <th>Categoria</th>
                      <th>Postedado</th>
                      <th>Acciones</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($posts as $post)
                    <tr>
                      <td>{{ $post->title }}</td>
                      <td>Categoria</td>
                      <td>{{ $post->posted }}</td>
                      <td>
                        <a href="{{ route("post.edit", $post->id) }}">Editar</a>
                        <a href="{{ route("post.show", $post->id) }}">Ver</a>
                        <form class="" action="{{ route("post.destroy", $post->id) }}" method="post">
                          <!--directiva laravel para que funcione el destroy-->
                          @method("DELETE")
                          @csrf
                            <button type="submit" name="button">Eliminar</button>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
                <!--funcion del paginado-->
                {{ $posts->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Dasboard</h1>
    @yield("content")

  </body>
</html>